### ISSUE TITLE
升级到0。1版本不能同步思源

### ISSUE THREAD

**Issue by uulaile** [winter60/plugin-flomo-sync#15]
是不是最新版本要更改什么设置
![image](https://github.com/winter60/plugin-flomo-sync/assets/96331996/2982afee-045b-467f-96d6-cf97d36473f2)
![image](https://github.com/winter60/plugin-flomo-sync/assets/96331996/a73e7702-427b-4ebd-bdf8-7e3eae56399a)

**Comment by winter60** [comment]
dailynote笔记本id写错了，只要id，斜杠和前面全不要

**Comment by winter60** [comment]
注意，以后发截图，accessToken也要打码
