### ISSUE TITLE
SiYuan 3.0.1同步插件V0.1.0点了之后没有反应

### ISSUE THREAD

**Issue by EthanMYX** [winter60/plugin-flomo-sync#16]
所有账号、密码、笔记本ID已经再三核对了没有问题，但点击了Flomo同步图标后没有任何反应（确定Flomo是Pro会员，同时里面是有笔记的。）麻烦看一下，谢谢！

**Comment by winter60** [comment]
请检查一下 配置`上次同步时间`, 以及`同步标签方案`是否为`排除标签` ,  如果没有什么问题，再新建一条记录，试一下同步

**Comment by winter60** [comment]
另外，使用该插件跟是不是会员没关系

**Comment by EthanMYX** [comment]
<img width="1421" alt="image" src="https://github.com/winter60/plugin-flomo-sync/assets/55939705/3ba6d131-eb1f-4832-a80e-6c4248340980">
请见截图。

**Comment by EthanMYX** [comment]
<img width="1024" alt="image" src="https://github.com/winter60/plugin-flomo-sync/assets/55939705/b6b801c0-534c-4240-a575-2b213bb44cbc">
Flomo中的内容

**Comment by winter60** [comment]
你同步方案选错了。选了`包含标签`却没有填具体的标签

**Comment by EthanMYX** [comment]
感谢、感谢！终于好了，这个插件太好了，解决了SiYuan本地强大，但随手记录重器轻用的问题。

**Comment by EthanMYX** [comment]
刚才试了一下Flomo传的图片没能同步过去，您有群或者在哪个群里面吗？因为这个插件解决了目前SiYuan使用中的一大痛点，所以需要请教的比较多。

**Comment by winter60** [comment]
> 刚才试了一下Flomo传的图片没能同步过去，您有群或者在哪个群里面吗？因为这个插件解决了目前SiYuan使用中的一大痛点，所以需要请教的比较多。

你可以F5刷新一下页面， 我在三群 538155062  ，刘烟火

**Comment by EthanMYX** [comment]
1、F5后图片显示正常了；
2、三群人满了，我在一群，我的QQ 325181 ；
3、另，建议同步可以自动添加日期和时间。

**Comment by winter60** [comment]
> 3、另，建议同步可以自动添加日期和时间。 

抱歉，暂时不考虑这个了。作为收集箱，我习惯在 dailynote 当中使用，当天用当天处理，日期时间还得删。

**Comment by EthanMYX** [comment]
好的，我去调整一下我的使用习惯。

**Comment by EthanMYX** [comment]
改用dailynote模式后发现目前的机制是根据同步时间对应到相同日期的dailynote中，建议考虑能按照当初在flomo中建立记录的时间去对应dailynote ；当然引发的问题是如果没有对应时间的dailynote，那么插件就得自己新建，可能实现起来有点麻烦。

**Comment by winter60** [comment]
不考虑了

**Comment by EthanMYX** [comment]
OK，已经可以了，解决了一大痛点。谢谢你！
