### ISSUE TITLE
希望能配置flomo的标签同步到思源后的呈现形式

### ISSUE THREAD

**Issue by windaway0103** [winter60/plugin-flomo-sync#20]
目前，flomo中包含标签的memo，同步到思源后，标签本身是默认转化成思源的标签形式的，然后用无序列表呈现，如下图：
![image](https://github.com/user-attachments/assets/4efc270d-ffaf-494e-add4-eaf1d9cf366a)

但是众所周知，思源中使用标签查找的体验并不好，不如使用传递型双链，在反链面板中汇总查看，来得方便。

我在想，能否允许配置下flomo的标签同步到思源后的形式，比如允许将`#我是标签#` 转化为`[[我是标签]]`，从而变成在思源中体验更好的双链形式，方便查找、汇总、查看。

或者再发散一下，允许将`#我是标签#` 转化为`##### 我是标签`，从而允许变成五级标题等形式插在文末。

感谢作者制作出这么好用的插件，期待您的回复。

**Comment by winter60** [comment]
是个不错的建议。不过开发对我有难度，暂时不做了。推荐安装番茄工具箱插件，然后用@@替代flomo的# 。

**Comment by winter60** [comment]
![recording](https://github.com/user-attachments/assets/f80bb03b-b76a-478f-87a7-037c333993fc)

**Comment by windaway0103** [comment]
Carol
***@***.***



&nbsp;
非常感谢，按照您的做法已经实现啦。迟来的中秋快乐，祝阖家幸福！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "winter60/plugin-flomo-sync"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月18日(星期三) 上午10:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [winter60/plugin-flomo-sync] 希望能配置flomo的标签同步到思源后的呈现形式 (Issue #20)





 
recording.gif (view on web)
