### ISSUE TITLE
同步指定时间段内创建的MEMO

### ISSUE THREAD

**Issue by TCOTC** [winter60/plugin-flomo-sync#5]
- 同步指定时间段内创建的MEMO
- 同步指定时间段内创建的MEMO至指定文档

> [能不能只把 flomo 当天记录的同步过去，现在是把整个同步过去的](https://ld246.com/article/1702016411231/comment/1702102281541?r=a2930610542#comments)

**Comment by winter60** [comment]
目前可以支持指定`起始修改时间` ，终止时间就不指定了，抱歉哈~
