### ISSUE TITLE
大量memos导入文档特别卡

### ISSUE THREAD

**Issue by winter60** [winter60/plugin-flomo-sync#6]
解决方式：将memos拆分成多个列表导入，暂定为`50`条memo，作为为一个列表块插入。
https://ld246.com/article/1702016411231/comment/1702120995773?r=kobi#comments

**Comment by TCOTC** [comment]
刚刚看到这个：[思源大纲笔记模式的性能测试](https://ld246.com/article/1691232134520?r=a2930610542) ，说明导入完之后应该就不卡了，是导入过程卡顿（也许是索引？）

**Comment by winter60** [comment]
> 刚刚看到这个：[思源大纲笔记模式的性能测试](https://ld246.com/article/1691232134520?r=a2930610542) ，说明导入完之后应该就不卡了，是导入过程卡顿（也许是索引？）

列表块，可能加载就是会卡，所以暂时就先这样做吧

**Comment by TCOTC** [comment]
我最多一天有52个 MEMO ，但 flomo 也只提倡每天记六七条，一个列表50条 MEMO 感觉确实够了。

**Comment by winter60** [comment]
> 我最多一天有52个 MEMO ，但 flomo 也只提倡每天记六七条，一个列表50条 MEMO 感觉确实够了。

我一天就几条，最多才10多条，这只是针对首次导入的情况
